---
title: Easy Park Plus - Use Case Diagram (Initial)
---
flowchart TD
    actor((User))
    UC1([Create Parking Lot])
    UC1.1([Create Parking Level])
    UC1.2([Create Parking Slot])
    UC1.3([Create EV Parking Slot])
    UC2([Park Vehicle])
    UC2.1([Get Empty Level])
    UC2.2a([Get Empty Slot])
    UC2.2b([Allocate Slot])
    UC2.3a([Get Empty EV Slot])
    UC2.3b([Allocate EV Slot])
    UC3([Leave])
    UC3.1([Get Slot By Vehicle])
    UC3.2([Release Slot])
    UC4([Edit Slot Information])
    UC5([View Lot Status])
    UC6([View EV Charge Status])
    UC7([Search by Registration/Color/Make/Model])

    User -- interacts with --> UC1
    UC1 -- includes --> UC1.1
    UC1.1 -- includes --> UC1.2
    UC1.1 -- includes --> UC1.3
    User -- interacts with --> UC2
    UC2 -- includes --> UC2.1
    UC2.1 -- includes --> UC2.2a
    UC2.1 -- includes --> UC2.2b
    UC2 -- includes --> UC2.3a
    UC2.3a -- includes --> UC2.3b
    User -- interacts with --> UC3
    UC3 -- includes --> UC3.1
    UC3.1 -- includes --> UC3.2
    User -- interacts with --> UC4
    User -- interacts with --> UC5
    User -- interacts with --> UC6
    User -- interacts with --> UC7

    classDef actor fill:#f9f,stroke:#333,stroke-width:2px;
    class User actor;
